version: "3.5"

services:
  api01: &api
    # Lembre-se de que seu serviço HTTP deve estar hospedado num repositório
    # publicamente acessível! Ex.: hub.docker.com
    image: vkobinski/pacientes
    hostname: api01
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=vkobinski
      - POSTGRES_DB=pacientes
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
    name: pacientes